version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    reviewers:
      - "opennms/dependabot-reviewers-maven"
    labels:
      - "dependency update"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
